name: 'dataset-verify'
description: 'Verifies a DataSet power query returns the correct expected number of rows'
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  token:
    description: 'The DataSet log read api token to use.'
    required: true
  scalyr-server:
    description: 'The DataSet URL to use (such as https://www.scalyr.com or https://eu.scalyr.com)'
    default: ''  # Empty indicates to use commandline default.
  start:
    description: 'The start of the query time range.'
    default: ''  # Empty indicates to use the commandline default
  end:
    description: 'The end of the query time range.'
    default: ''  # Empty indicates to use the commandline default
  query:
    description: 'The power query to execute.'
    required: true
  row-count-eq:
    description: 'If specified, requires the row count to equal this number.'
    default: ''
  row-count-lt:
    description: 'If specified, requires the row count to be less than this number.'
    default: ''
  row-count-gt:
    description: 'If specified, requires the row count to greater than this number.'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-t'
    - '"{{input.token}}"'
    - '--scalyr-server'
    - '"{{input.scalyr-server}}"'
    - '--start'
    - '"{{input.start}}"'
    - '--end'
    - '"{{input.end}}"'
    - '-eq'
    - '"{{input.row-count-eq}}"'
    - '-lt'
    - '"{{input.row-count-lt}}"'
    - '-gt'
    - '"{{input.row-count-gt}}"'
    - '"{{input.query}}"'

  entrypoint: '/action/remove_empty_args_and_invoke.sh'

